development:
  <<: *defaults
  database: scores_development

test:
  <<: *defaults
  database: scores_test
  w: 0

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGODB_URI'] %>
